version: '3.5'
services:
  app:
    #restart: unless-stopped
    build:
      context: .
    ports:
      - "8080:80"
    environment:
      TZ: Europe/Paris
      CAMS-RECORDER_CAMERA_ONVIFURL: http://192.168.xx.yy:zz
      CAMS-RECORDER_CAMERA_USER: xx
      CAMS-RECORDER_CAMERA_PASS: yy

    volumes:
      - ./data:/data
